p_rayno_cas_auth:
  server_login_url: '%env(string:CAS_HOST)%'
  server_validation_url: '%env(string:CAS_HOST)%'
  server_logout_url: '%env(bool:CAS_HANDLE_LOGOUT_REQUEST)%'
  #xml_namespace: cas
  #options:[] # see http://docs.guzzlephp.org/en/latest/request-options.html


#  l3_cas:
#    host: '%env(string:CAS_HOST)%'
#    path: '%env(string:CAS_PATH)%'
#    port: '%env(int:CAS_PORT)%'
#    ca: '%env(bool:CAS_CA)%'
#    handleLogoutRequest: '%env(bool:CAS_HANDLE_LOGOUT_REQUEST)%'
#    casLogoutTarget: '%env(string:CAS_LOGOUT_TARGET)%'
#    force: false
#    gateway: '%env(bool:CAS_GATEWAY)%'
