security:
  encoders:
    App\Entity\Utilisateur: bcrypt

  role_hierarchy:
  #- ROLE_SUPER_ADMIN:ROLE_PERMANENT

  providers:
    chain_provider:
      chain:
        providers: [personnel_user, etudiant_user]
    personnel_user:
      entity: { class: App\Entity\Personnel, property: username }
    etudiant_user:
      entity: { class: App\Entity\Etudiant, property: username }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      #http_basic: ~
      # les urls auxquels s'appliquent ce firewall, dans ce cas, ce sont toutes les urls
      pattern: ^/

      # La connexion n'est pas requise sur toutes les pages
      # par exemple la page d'accueil
      anonymous: true
      logout:
        path: security_logout
        target: security_login
      provider: chain_provider
      guard:
          authenticators:
              - App\Security\LoginFormAuthenticator

  access_control:
    # Les regles de securité
    # Là dans ce cas seul les utilisateurs ayant le rôle ROLE_ADMIN
    # peuvent acceder à toutes les pages commençant par /admin
    - { path: '^/admin', roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: '^/[a-z]{2}/connexion', roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: '^/[a-z]{2}/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: '^/[a-z]{2}/api', roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: '^/[a-z]{2}/', roles: IS_AUTHENTICATED_FULLY }
    - { path: '^/[a-z]{2}/administration', roles: ROLE_PERMANENT }
    - { path: '^/[a-z]{2}/iut', roles: ROLE_IUT }
    - { path: '^/[a-z]{2}/super-administration', roles: ROLE_SUPER_ADMIN }
    - { path: '^/[a-z]{2}/admin', roles: ROLE_PERMANENT }
    - { path: '^/[a-z]{2}/api/', roles: IS_AUTHENTICATED_ANONYMOUSLY }
