security:
  enable_authenticator_manager: true

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  role_hierarchy:
    ROLE_SUPER_ADMIN: ROLE_ADMINISTRATIF
    ROLE_QUALITE: ROLE_ADMINISTRATIF
    ROLE_SCOLARITE: ROLE_ADMINISTRATIF
    ROLE_RH: ROLE_ADMINISTRATIF
    ROLE_FINANCE: ROLE_ADMINISTRATIF

  providers:
    chain_provider:
      chain:
        providers: [personnel_user, etudiant_user]
    personnel_user:
      entity: { class: App\Entity\Personnel, property: username }
    etudiant_user:
      entity: { class: App\Entity\Etudiant, property: username }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: chain_provider
      custom_authenticator:
        - App\Security\LoginFormAuthenticator
        - App\Security\LoginCasAuthenticator
      entry_point: App\Security\LoginFormAuthenticator
      pattern: ^/
#      remember_me:
#        secret: '%kernel.secret%'
      logout:
        path: security_logout
        target: security_login



  access_control:
    # Les regles de securité
    # Là dans ce cas seul les utilisateurs ayant le rôle ROLE_ADMIN
    # peuvent acceder à toutes les pages commençant par /admin
    - { path: '^/[a-z]{2}/but', roles: PUBLIC_ACCESS }
    - { path: '^/[a-z]{2}/borne', roles: PUBLIC_ACCESS }
    - { path: '^/[a-z]{2}/rdd', roles: PUBLIC_ACCESS }
    - { path: '^/[a-z]{2}/sso/redirect/cas', roles: PUBLIC_ACCESS }
    - { path: '^/[a-z]{2}/connexion', roles: PUBLIC_ACCESS }
    - { path: '^/[a-z]{2}/mentions-legales/', roles: PUBLIC_ACCESS }
    - { path: '^/[a-z]{2}/login', roles: PUBLIC_ACCESS }
    - { path: '^/[a-z]{2}/api', roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: '^/[a-z]{2}/administration', roles: [ROLE_PERMANENT, ROLE_SUPER_ADMIN] }
    - { path: '^/[a-z]{2}/ldap', roles: [ ROLE_PERMANENT, ROLE_SUPER_ADMIN, ROLE_RH ] }
    - { path: '^/[a-z]{2}/administratif', roles: [ ROLE_ADMINISTRATIF ] }
    - { path: '^/[a-z]{2}/', roles: IS_AUTHENTICATED_FULLY }

