twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        # the value is the service's id
        version: '@App\Classes\Version'
        user_data: '@App\Classes\DataUserSession'
        iconShow: 'fas fa-info'
        iconEdit: 'fas fa-edit'
        iconDelete: 'fas fa-trash-alt'
        iconPrint: 'fas fa-print'
        iconDuplicate: 'fas fa-copy'
        iconAdmin: 'fas fa-wrench'
        iconDashboard: 'fas fa-home fa-3x'
        linuxpath: '%env(resolve:BASE_URL)%'

        exception_controller: null # This is needed to fix the deprecation in Symfony 4.4

when@test:
    twig:
        strict_variables: true
