twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        # the value is the service's id
        version: '@App\Classes\Version'
        user_data: '@App\Classes\DataUserSession'
        iconShow: 'mdi mdi-eye'
        iconEdit: 'mdi mdi-pencil'
        iconDelete: 'mdi mdi-delete'
        iconPrint: 'mdi mdi-printer'
        iconDuplicate: 'mdi mdi-content-copy'
        iconAdmin: 'mdi mdi-wrench'
        iconDashboard: 'mdi mdi-home mdi-36px'
        linuxpath: '%env(resolve:BASE_URL)%'

        exception_controller: null # This is needed to fix the deprecation in Symfony 4.4

when@test:
    twig:
        strict_variables: true
