language: php
sudo: false
dist: bionic

# Start mysql service
services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - SYMFONY_VERSION="5.1.*" DB=mysql

matrix:
  fast_finish: true
  include:
    #   - php: 7.1
    - php: 7.4
#    - php: nightly
#  allow_failures:
#    - php: nightly

before_install:
  #  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
  - composer self-update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testing;'

install:
  - cp .env.test.dist .env.test
  - cp phpunit.xml.dist phpunit.xml
  - composer update --no-script #--prefer-dist --no-interaction
  #- php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  #- .bin/phpunit #--configuration phpunit.xml #a confirmer ? prendrait le .env.test
  #- ./vendor/bin/simple-phpunit
  - ./vendor/bin/simple-phpunit --coverage-text --colors


notifications:
  email:
    recipients:
      - david.annebicque@gmail.com
    on_success: always
    on_failure: always
