homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /fr/tableau-de-bord
        permanent: true

fr_homepage:
    path: /fr
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /fr/tableau-de-bord
        permanent: true

en_homepage:
    path: /en
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /en/tableau-de-bord
        permanent: true

controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    defaults:
        _locale: fr
    requirements:
        _locale: fr|en|de|es
