name: IntranetV3

on:
  push:
  pull_request:

jobs:

  integration:
    name: Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          extensions: "json,couchbase,memcached,mongodb,redis,rdkafka,xsl"
          ini-values: "memory_limit=-1"
          php-version: "7.4"
          tools: flex,pecl

      - name: Configure composer
        run: |
          ([ -d ~/.composer ] || mkdir ~/.composer) && cp .github/composer-config.json ~/.composer/config.json
          SYMFONY_VERSION=$(cat composer.json | grep '^ *\"branch-version\". *\"[1-9]' | grep -o '[0-9.]*')
          echo "::set-env name=SYMFONY_VERSION::$SYMFONY_VERSION"
          echo "::set-env name=COMPOSER_ROOT_VERSION::$SYMFONY_VERSION.x-dev"
      - name: Determine composer cache directory
        id: composer-cache
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.directory }}
          key: 7.4-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: 7.4-composer-

      - name: Install dependencies
        run: |
          echo "::group::composer update"
          composer update --no-progress --no-suggest --ansi
          echo "::endgroup::"
          echo "::group::install phpunit"
          ./phpunit install
          echo "::endgroup::"
      - name: Run tests
        run: ./phpunit --group integration
        env:
          REDIS_HOST: localhost
          REDIS_CLUSTER_HOSTS: 'localhost:7000 localhost:7001 localhost:7002 localhost:7003 localhost:7004 localhost:7005'
          MESSENGER_REDIS_DSN: redis://127.0.0.1:7006/messages
          MESSENGER_AMQP_DSN: amqp://localhost/%2f/messages
          MESSENGER_SQS_DSN: "sqs://localhost:9494/messages?sslmode=disable&poll_timeout=0.01"
          MESSENGER_SQS_FIFO_QUEUE_DSN: "sqs://localhost:9494/messages.fifo?sslmode=disable&poll_timeout=0.01"
          MEMCACHED_HOST: localhost
          MONGODB_HOST: localhost
          KAFKA_BROKER: localhost:9092
          POSTGRES_HOST: localhost

      - name: Run HTTP push tests
        if: matrix.php == '7.4'
        run: |
          [ -d .phpunit ] && mv .phpunit .phpunit.bak
          wget -q https://github.com/symfony/binary-utils/releases/download/v0.1/vulcain_0.1.3_Linux_x86_64.tar.gz -O - | tar xz && mv vulcain /usr/local/bin
          docker run --rm -e COMPOSER_ROOT_VERSION -e SYMFONY_VERSION -v $(pwd):/app -v $(which composer):/usr/local/bin/composer -v /usr/local/bin/vulcain:/usr/local/bin/vulcain -w /app php:7.4-alpine ./phpunit src/Symfony/Component/HttpClient/Tests/CurlHttpClientTest.php --filter testHttp2Push
          sudo rm -rf .phpunit
          [ -d .phpunit.bak ] && mv .phpunit.bak .phpunit
