name: IntranetV3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    -   name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            coverage: "none"
            extensions: "json,couchbase,memcached,mongodb,redis,rdkafka,xsl"
            ini-values: "memory_limit=-1"
            php-version: "${{ matrix.php }}"
            tools: flex,pecl

    -   name: Configure composer
        run: |
            ([ -d ~/.composer ] || mkdir ~/.composer) && cp .github/composer-config.json ~/.composer/config.json
            SYMFONY_VERSION=$(cat composer.json | grep '^ *\"branch-version\". *\"[1-9]' | grep -o '[0-9.]*')
            echo "::set-env name=SYMFONY_VERSION::$SYMFONY_VERSION"
            echo "::set-env name=COMPOSER_ROOT_VERSION::$SYMFONY_VERSION.x-dev"
    -   name: Determine composer cache directory
        id: composer-cache
        run: echo "::set-output name=directory::$(composer config cache-dir)"

    -   name: Cache composer dependencies
        uses: actions/cache@v1
        with:
            path: ${{ steps.composer-cache.outputs.directory }}
            key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: ${{ matrix.php }}-composer-

    -   name: Install dependencies
        run: |
            echo "::group::composer update"
            composer require --dev --no-update mongodb/mongodb:@stable
            composer update --no-progress --no-suggest --ansi
            echo "::endgroup::"
            echo "::group::install phpunit"
            ./phpunit install
            echo "::endgroup::"
            
    -   name: Run tests
        run: ./phpunit --group integration

